services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: mattermost
      POSTGRES_USER: mattermost
      POSTGRES_PASSWORD: mattermost
  mattermost:
    image: mattermost/mattermost-team-edition:11.6.1
    platform: linux/amd64
    environment:
      MM_SERVICESETTINGS_SITEURL: http://localhost:8065
      MM_LOGSETTINGS_CONSOLELEVEL: DEBUG
      MM_NOTIFICATIONLOGSETTINGS_CONSOLELEVEL: DEBUG
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://mattermost:mattermost@postgres:5432/mattermost?sslmode=disable
      MM_PASSWORDSETTINGS_MINIMUMLENGTH: "5"
      MM_PASSWORDSETTINGS_NUMBER: "false"
      MM_PASSWORDSETTINGS_UPPERCASE: "false"
      MM_PASSWORDSETTINGS_SYMBOL: "false"
      MM_SERVICESETTINGS_ENABLELOCALMODE: "true"
      MM_SERVICESETTINGS_ENABLEUSERACCESSTOKENS: "true"
      MM_SERVICESETTINGS_ENABLEAPICHANNELDELETION: "true"
      MM_SERVICESETTINGS_ENABLEAPIUSERDELETION: "true"
      MM_SERVICESETTINGS_ENABLEAPITEAMDELETION: "true"
    ports:
      - 8065:8065
